Fix cmake breakage introduced in r360: undefined reference to `print_nfc_iso14443a_info'
git-svn-id: http://libnfc.googlecode.com/svn/trunk@384 45cb0fa4-f8fe-11dd-984d-ab748d24aa7e